### ISSUE TITLE
User can enter invalid data and crash coffeebot

### ISSUE THREAD

**Issue by tsukasa-au** [ncss/ncss-coffeerun#8]
The coffee order `yfw plz` caused coffeebot to crash. Coffeebot should probably not crash on "invalid" user input.

```
2017-01-04T14:09:36.507403+00:00 app[worker.1]: DEBUG:main:Event: {u'channel': u'C37UBN41F', u'user': u'U3ALDU03W', u'team': u'T38M9BTEZ', u'text': u'<@U3LB5LDQD> yfw plz', u'ts': u'1483538976.000228', u'type': u'message'}
2017-01-04T14:09:36.507605+00:00 app[worker.1]: DEBUG:handle_message:message event: {u'channel': u'C37UBN41F', u'user': u'U3ALDU03W', u'team': u'T38M9BTEZ', u'text': u'<@U3LB5LDQD> yfw plz', u'ts': u'1483538976.000228', u'type': u'message'}
2017-01-04T14:09:36.507994+00:00 app[worker.1]: INFO:handle_message:Mentions: [u'U3LB5LDQD']
2017-01-04T14:09:36.508579+00:00 app[worker.1]: INFO:order_coffee:Matches: {u'runid': None}
2017-01-04T14:09:36.573851+00:00 app[worker.1]: Traceback (most recent call last):
2017-01-04T14:09:36.573853+00:00 app[worker.1]:   File "coffeebot.py", line 284, in <module>
2017-01-04T14:09:36.574036+00:00 app[worker.1]:     main()
2017-01-04T14:09:36.574059+00:00 app[worker.1]:   File "coffeebot.py", line 267, in main
2017-01-04T14:09:36.574189+00:00 app[worker.1]:     handler(client, event)
2017-01-04T14:09:36.574210+00:00 app[worker.1]:   File "coffeebot.py", line 236, in handle_message
2017-01-04T14:09:36.574271+00:00 app[worker.1]:     handle_mention_message(slackclient, user, channel, text)
2017-01-04T14:09:36.574299+00:00 app[worker.1]:   File "coffeebot.py", line 202, in handle_mention_message
2017-01-04T14:09:36.574433+00:00 app[worker.1]:     ORDERS_DISPATCH[order_re](slackclient, user, channel, match)
2017-01-04T14:09:36.574437+00:00 app[worker.1]:   File "coffeebot.py", line 95, in order_coffee
2017-01-04T14:09:36.574613+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 200, in _initialize_instance
2017-01-04T14:09:36.574472+00:00 app[worker.1]:     coffee = Coffee(match.group(1), 0, run.id)
2017-01-04T14:09:36.574492+00:00 app[worker.1]:   File "<string>", line 4, in __init__
2017-01-04T14:09:36.574744+00:00 app[worker.1]:     self.price = self.lookup_price()
2017-01-04T14:09:36.574829+00:00 app[worker.1]:     price_key = coffeespecs.Coffee.fromJSON(self.coffee).get_price_key()
2017-01-04T14:09:36.574684+00:00 app[worker.1]:   File "/app/application/models.py", line 235, in __init__
2017-01-04T14:09:36.574667+00:00 app[worker.1]:     return manager.original_init(*mixed[1:], **kwargs)
2017-01-04T14:09:36.574763+00:00 app[worker.1]:   File "/app/application/models.py", line 246, in lookup_price
2017-01-04T14:09:36.574849+00:00 app[worker.1]:   File "/app/coffeespecs.py", line 98, in fromJSON
2017-01-04T14:09:36.574890+00:00 app[worker.1]:     raise Exception('Invalid coffee')
2017-01-04T14:09:36.574917+00:00 app[worker.1]: Exception: Invalid coffee
2017-01-04T14:09:36.743761+00:00 heroku[worker.1]: Process exited with status 1
2017-01-04T14:09:36.758062+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by katharosada** [comment]
This no longer seems to happen. 👍
